1 **Unique**

In [3]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105",
                   "P106", "P107", "P108", "P109", "P110"],

    "Age": [45, 62, 34, 55, 41, 68, 29, 52, 47, 73],

    "City": ["Hyderabad", "Warangal", "Hyderabad", "Vijayawada",
             "Hyderabad", "Nizamabad", "Hyderabad", "Warangal",
             "Hyderabad", "Karimnagar"],

    "Surgery_Type": [
        "Cholecystectomy", "CABG", "Appendectomy",
        "Hernia Repair", "Knee Replacement", "PTCA",
        "Appendectomy", "Cholecystectomy",
        "Hernia Repair", "Knee Replacement"
    ],

    "Operation_Duration_Min": [90, 240, 75, 110, 180,
                               150, 70, 95, 120, 200],

    "Length_of_Stay_Days": [2, 7, 1, 3, 5,
                            4, 1, 2, 3, 6],

    "Admission_Type": [
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Emergency", "Emergency", "Planned",
        "Planned", "Planned"
    ]
}

df = pd.DataFrame(data)
print(df)

  Patient_ID  Age        City      Surgery_Type  Operation_Duration_Min  \
0       P101   45   Hyderabad   Cholecystectomy                      90
1       P102   62    Warangal              CABG                     240
2       P103   34   Hyderabad      Appendectomy                      75
3       P104   55  Vijayawada     Hernia Repair                     110
4       P105   41   Hyderabad  Knee Replacement                     180
5       P106   68   Nizamabad              PTCA                     150
6       P107   29   Hyderabad      Appendectomy                      70
7       P108   52    Warangal   Cholecystectomy                      95
8       P109   47   Hyderabad     Hernia Repair                     120
9       P110   73  Karimnagar  Knee Replacement                     200

   Length_of_Stay_Days Admission_Type
0                    2        Planned
1                    7      Emergency
2                    1      Emergency
3                    3        Planned
4                    5        Planned
5                    4      Emergency
6                    1      Emergency
7                    2        Planned
8                    3        Planned
9                    6        Planned

In [4]:
df["City"].unique()

array(['Hyderabad', 'Warangal', 'Vijayawada', 'Nizamabad', 'Karimnagar'],
      dtype=object)

2 **nun** **unique**

In [6]:
df["City"].nunique()  # values count

5

3 value_counts()

In [8]:
#kaunsi city se kitane patient ayee
# har value kitne bar ayyi count karta hai

df['City'].value_counts()

City
Hyderabad     5
Warangal      2
Vijayawada    1
Nizamabad     1
Karimnagar    1
Name: count, dtype: int64

In [9]:
# konsi surgery kitni bar hui

df['Surgery_Type'].value_counts()

Surgery_Type
Cholecystectomy     2
Appendectomy        2
Knee Replacement    2
Hernia Repair       2
CABG                1
PTCA                1
Name: count, dtype: int64

QUESTION admission type

In [10]:
df['Admission_Type'].unique()

array(['Planned', 'Emergency'], dtype=object)

total kitne different types hai

In [11]:
df['Admission_Type'].nunique()

2

har type ke kitne patient hai

In [12]:
df['Admission_Type'].value_counts()

Admission_Type
Planned      6
Emergency    4
Name: count, dtype: int64

std() data kitana spread hua hai

In [ ]:
# 5 - patient ki surgery ka time 90,95,100,105,110

In [13]:
df['Operation_Duration_Min'].std()

57.503623074260865

**DATA CLEANING**

Isnull()


NONe --- data avaible nahi hota hai/not a number

In [16]:
import pandas as pd

data = {
    "Patient_ID": ["P101", "P102", "P103", "P104", "P105"],
    "Age": [45, 62, None, 55, 41],
    "City": ["Hyderabad", "Warangal", "Hyderabad", None, "Hyderabad"],
    "Operation_Duration_Min": [90, 240, 75, None, 180]
}

df = pd.DataFrame(data)

print(df)

  Patient_ID   Age       City  Operation_Duration_Min
0       P101  45.0  Hyderabad                    90.0
1       P102  62.0   Warangal                   240.0
2       P103   NaN  Hyderabad                    75.0
3       P104  55.0       None                     NaN
4       P105  41.0  Hyderabad                   180.0

In [17]:
print(df.isnull())

# true shows value missing
# falsee shows values that are available

   Patient_ID    Age   City  Operation_Duration_Min
0       False  False  False                   False
1       False  False  False                   False
2       False   True  False                   False
3       False  False   True                    True
4       False  False  False                   False

In [19]:
print(df['Age'].isnull())

0    False
1    False
2     True
3    False
4    False
Name: Age, dtype: bool

In [20]:


# kitni missing values

In [22]:
print(df.isnull().sum())  # count missing value in each column

Patient_ID                0
Age                       1
City                      1
Operation_Duration_Min    1
dtype: int64